services:
  - type: web
    name: dostyk-bakery-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: your_token_here
      - key: ADMIN_ID
        value: 6529188202
